# Generated by Django 5.2.7 on 2025-10-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatepass', '0002_parent_remove_student_parent_contact_student_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatepass',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
