# Generated by Django 5.2.7 on 2025-10-04 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatepass', '0007_create_profiles_for_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatepass',
            name='purpose',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='gatepass',
            name='status',
            field=models.CharField(choices=[('PENDING_PARENT', 'Pending Parent Approval'), ('PENDING_WARDEN', 'Pending Warden Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='PENDING_PARENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='gatepass.profile'),
        ),
    ]
