# Generated by Django 5.0.1 on 2025-10-04 18:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatepass', '0008_alter_gatepass_purpose_alter_gatepass_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatepass',
            name='from_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='gatepass',
            name='purpose',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='gatepass',
            name='to_time',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='ApprovalToken',
            fields=[
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('used', models.BooleanField(default=False)),
                ('action_taken', models.CharField(blank=True, choices=[('approve', 'Approved'), ('reject', 'Rejected')], max_length=10, null=True)),
                ('gatepass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_tokens', to='gatepass.gatepass')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_tokens', to='gatepass.parent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Approval',
        ),
    ]
