# Generated by Django 5.2.7 on 2025-10-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatepass', '0003_alter_gatepass_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='parents',
            field=models.ManyToManyField(related_name='children', to='gatepass.parent'),
        ),
    ]
