# Generated by Django 5.1 on 2025-10-03 15:30

from django.db import migrations

def create_profiles_for_existing_students(apps, schema_editor):
    """
    Create a User and Profile for any Student that doesn't have one.
    """
    Student = apps.get_model('gatepass', 'Student')
    User = apps.get_model('auth', 'User')
    Profile = apps.get_model('gatepass', 'Profile')

    for student in Student.objects.filter(profile__isnull=True):
        # Create a basic user. You might want to customize this.
        # We use roll_no to ensure the username is unique.
        username = f"student_{student.roll_no}"
        user = User.objects.create_user(username=username, password="password") # Set a default password

        # Create the profile
        profile = Profile.objects.create(user=user, user_type="STUDENT")

        # Link the profile to the student
        student.profile = profile
        student.save(update_fields=['profile'])


class Migration(migrations.Migration):

    dependencies = [
        ('gatepass', '0005_rename_expires_at_gatepass_request_expires_at_and_more'),
    ]

    operations = [
        migrations.RunPython(create_profiles_for_existing_students),
    ]
