# Generated by Django 5.2.7 on 2025-10-03 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gatepass', '0006_create_profiles_for_students'),
    ]

    operations = [
    ]
